persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

listener 1883
allow_anonymous true

# Optional: enable websockets on 9001
listener 9001
protocol websockets
