services:
  db:
    image: postgis/postgis:15-3.4
    container_name: flood_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    networks:
      - floodnet

  mqtt:
    image: eclipse-mosquitto:2
    container_name: flood_mqtt
    restart: always
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - floodnet

  backend:
    build: ./backend
    container_name: flood_backend
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PG_HOST: db
      PG_PORT: 5432
      PG_USER: ${POSTGRES_USER}
      PG_PASS: ${POSTGRES_PASSWORD}
      PG_DB: ${POSTGRES_DB}

      MQTT_BROKER: mqtt
      MQTT_PORT: 1883
      MQTT_USER: ${MQTT_USER}
      MQTT_PASS: ${MQTT_PASS}
      MQTT_TOPIC: nodes/flood

      JWT_SECRET: ${JWT_SECRET}
      PORT: 3000
    depends_on:
      - db
      - mqtt
    ports:
      - "3000:3000"
    networks:
      - floodnet

  frontend:
    build: ./react-dashboard
    container_name: flood_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - floodnet

volumes:
  db_data:
  mosquitto_data:
  mosquitto_log:

networks:
  floodnet:
    driver: bridge
